model:
  feat_dim: 512
  num_classes: 3
  text_enc_name: ViT-B/32
  pooling_method: attention
  use_bag_prompt: false
  use_cls_prompt: false
  use_CoOP: false
  # prompt guide param, pooling_method: promptguide
  pooling_strategy: first_token
  device: cuda

  bag_texts:
    "TPS score is 0%": null
    "TPS score is 1%": null
    "TPS score is 5%": null
    "TPS score is 10%": null
    "TPS score is 20%": null
    "TPS score is 30%": null
    "TPS score is 40%": null
    "TPS score is 50%": null
    "TPS score is 60%": null
    "TPS score is 70%": null
    "TPS score is 80%": null

clinical_path: "/home/auwqh/dataset/PDL1/meta_data/excel_data/PDL1_score_clinical.xlsx"
batch_size: 1
num_workers: 4
lr: 0.0001
scheduler:
  warmup_steps: 200
  base_lr: 1.0e-6
  max_lr: 1.0e-4
  T_max: 200
  eta_min: 1.0e-7
n_epochs: 100
seed: 2022
early_stop: 20
lambda_kl: 1
