model:
  feat_dim: 512
  text_enc_name: ViT-B/32
  instance_template: "an immunohistochemical pathological image of "
  instance_texts:
    "tumor region":
      - "irregularly arranged cells with high density, exhibiting variable sizes and morphologies of cell nuclei"
      - "cells are densely packed with tight arrangements, exhibiting invasive characteristics typical of tumor tissue"
      - "irregular borders and deformed cell nuclei"
      - "nuclei are abnormally large and densely distributed"
    "normal epithelial region":
      - "cells are arranged in an orderly manner with uniform nucleus size"
      - "monomorphic nuclei, arranged in a compact manner"
    "immune cell region":
      - "small and round cells"
      - "clusters of immune cells"
    "stroma region":
      - "fibrous structures, lightly stained, with sparse cell distribution"
      - "broad stromal regions with sparse cell population, uniformly and lightly stained"
    "necrotic region":
      - "cell structures are blurry, with uneven staining, indicating necrotic features"
      - "nuclei are fragmented, and staining appears as mottled, vacuolated patterns"
    "background":
      - "acellular or devoid of tissue, lightly stained, serving as background"
      - "blank areas with no apparent cells or staining"
      - "lack of tissue structure, with evenly stained light-colored background"
      - "large areas of blank space, lacking cells and tissue, with very low staining intensity"
  bag_template: "a immunohistochemical pathological image of "
  bag_texts:
    "TPS score is 0%":
      - "the tumor cells do not express PD-L1 at all, with no staining observed in the tumor region"
    "TPS score is 1%":
      - "only a minimal number of cells exhibit faint brown staining, indicating sparse expression of PD-L1"
    "TPS score is 5%":
      - "the tumor area is predominantly composed of non-stained cells, with roughly 5% of cells exhibiting moderate brown staining"
    "TPS score is 10%":
      - "approximately 10% of the cells display brown staining, interspersed among non-stained cells"
    "TPS score is 20%":
      - "approximately 20% of the cells in the tumor region are stained brown, contrasting with the non-stained cells"
    "TPS score is 30%":
      - "about 30% of the tumor cells exhibit moderate to strong brown staining, distributed among the non-stained cells"
    "TPS score is 40%":
      - "approximately 40% of the cells in the tumor region display brown staining, creating a distinct contrast with the non-stained cells"
    "TPS score is 50%":
      - "within the tumor area, roughly half of the cells exhibit strong brown staining, indicating significant expression of PD-L1"
    "TPS score is 60%":
      - "approximately 60% of the tumor cells show intense brown staining, markedly higher than the non-stained cells"
    "TPS score is 70%":
      - "approximately 70% of the cells exhibit strong brown staining, indicative of widespread PD-L1 expression"
    "TPS score is 80%":
      - "approximately 80% of the tumor cells display dense brown staining, indicative of extensive PD-L1 expression, nearly encompassing the entire tumor area"
  device: cpu