model:
  feat_dim: 512
  num_classes: 4
  text_enc_name: ViT-B/32
  pooling_method: mean
  use_bag_prompt: false
  use_cls_prompt: false
  use_CoOP: false
  # prompt guide param, pooling_method: promptguide
  pooling_strategy: first_token
  device: cuda

clinical_path: null
batch_size: 1
num_workers: 4
lr: 0.0001
scheduler:
  warmup_steps: 200
  base_lr: 1.0e-6
  max_lr: 1.0e-4
  T_max: 200
  eta_min: 1.0e-7
n_epochs: 100
seed: 1
early_stop: 20
lambda_kl: 1
