model:
  feat_dim: 512
  num_classes: 3
  text_enc_name: ViT-B/32
  pooling_method: similarity
  use_bag_prompt: false
  use_cls_prompt: false
  use_CoOP: true
  # prompt guide param, pooling_method: promptguide
  pooling_strategy: first_token
  device: cuda

  instance_template: "an immunohistochemical pathological image of"
  instance_texts:
    "tumor region":
      - "irregularly arranged cells with high density, exhibiting variable sizes and morphologies of cell nuclei"
      - "cells are densely packed with tight arrangements, exhibiting invasive characteristics typical of tumor tissue"
      - "irregular borders and deformed cell nuclei"
      - "nuclei are abnormally large and densely distributed"
    "normal epithelial region":
      - "cells are arranged in an orderly manner with uniform nucleus size"
      - "monomorphic nuclei, arranged in a compact manner"
    "immune cell region":
      - "small and round cells"
      - "clusters of immune cells"
    "stroma region":
      - "fibrous structures, lightly stained, with sparse cell distribution"
      - "broad stromal regions with sparse cell population, uniformly and lightly stained"
    "necrotic region":
      - "cell structures are blurry, with uneven staining, indicating necrotic features"
      - "nuclei are fragmented, and staining appears as mottled, vacuolated patterns"
    "background":
      - "acellular or devoid of tissue, lightly stained, serving as background"
      - "blank areas with no apparent cells or staining"
      - "lack of tissue structure, with evenly stained light-colored background"
      - "large areas of blank space, lacking cells and tissue, with very low staining intensity"
  bag_template: "an immunohistochemical pathological image of"
  bag_texts:
    "TPS score is 0%":
      - "the tumor cells do not express PD-L1 at all, with no staining observed in the tumor region"
    "TPS score is 1%":
      - "only a minimal number of cells exhibit faint brown staining, indicating sparse expression of PD-L1"
    "TPS score is 5%":
      - "the tumor area is predominantly composed of non-stained cells, with roughly 5% of cells exhibiting moderate brown staining"
    "TPS score is 10%":
      - "approximately 10% of the cells display brown staining, interspersed among non-stained cells"
    "TPS score is 20%":
      - "approximately 20% of the cells in the tumor region are stained brown, contrasting with the non-stained cells"
    "TPS score is 30%":
      - "about 30% of the tumor cells exhibit moderate to strong brown staining, distributed among the non-stained cells"
    "TPS score is 40%":
      - "approximately 40% of the cells in the tumor region display brown staining, creating a distinct contrast with the non-stained cells"
    "TPS score is 50%":
      - "within the tumor area, roughly half of the cells exhibit strong brown staining, indicating significant expression of PD-L1"
    "TPS score is 60%":
      - "approximately 60% of the tumor cells show intense brown staining, markedly higher than the non-stained cells"
    "TPS score is 70%":
      - "approximately 70% of the cells exhibit strong brown staining, indicative of widespread PD-L1 expression"
    "TPS score is 80%":
      - "approximately 80% of the tumor cells display dense brown staining, indicative of extensive PD-L1 expression, nearly encompassing the entire tumor area"
  cls_template: "an immunohistochemical pathological image of"
  cls_texts:
    "PD-L1 negative":
      - "the tumor cells completely lack PD-L1 expression, with virtually no staining observed throughout the entire tumor region"
    "low PD-L1 expression":
      - "within the tumor area, some cells exhibit moderate brown staining intensity"
    "high PD-L1 expression":
      - "in the tumor region, the majority of cells display strong brown staining, with stained cells occupying a substantial portion of the field of view"

clinical_path: "/home/auwqh/dataset/PDL1/meta_data/excel_data/PDL1_score_clinical.xlsx"
batch_size: 1
num_workers: 4
lr: 0.0001
scheduler:
  warmup_steps: 200
  base_lr: 1.0e-6
  max_lr: 1.0e-4
  T_max: 200
  eta_min: 1.0e-7
n_epochs: 100
seed: 2022
early_stop: 20
lambda_kl: 1
